# Generated by Django 5.0.1 on 2024-01-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_delete_resetmail'),
    ]

    operations = [
        migrations.CreateModel(
            name='iconPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('filepath', models.CharField(max_length=512)),
            ],
        ),
    ]
