# Generated by Django 5.0.1 on 2024-01-31 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iconpath',
            old_name='username',
            new_name='userid',
        ),
    ]
