# Generated by Django 5.0.1 on 2024-02-01 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_username_iconpath_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iconpath',
            name='filepath',
            field=models.FileField(max_length=512, upload_to=''),
        ),
    ]
